export const StagedProposalProcessor_ABI = [
	{ inputs: [], name: 'AlreadyInitialized', type: 'error' },
	{ inputs: [{ internalType: 'address', name: 'body', type: 'address' }], name: 'BodyResultTypeNotSet', type: 'error' },
	{
		inputs: [
			{ internalType: 'address', name: 'dao', type: 'address' },
			{ internalType: 'address', name: 'where', type: 'address' },
			{ internalType: 'address', name: 'who', type: 'address' },
			{ internalType: 'bytes32', name: 'permissionId', type: 'bytes32' },
		],
		name: 'DaoUnauthorized',
		type: 'error',
	},
	{ inputs: [], name: 'DelegateCallFailed', type: 'error' },
	{
		inputs: [
			{ internalType: 'uint256', name: 'stageId', type: 'uint256' },
			{ internalType: 'address', name: 'body', type: 'address' },
		],
		name: 'DuplicateBodyAddress',
		type: 'error',
	},
	{ inputs: [], name: 'FunctionDeprecated', type: 'error' },
	{ inputs: [], name: 'InsufficientGas', type: 'error' },
	{ inputs: [], name: 'InterfaceNotSupported', type: 'error' },
	{
		inputs: [
			{
				components: [
					{ internalType: 'address', name: 'target', type: 'address' },
					{ internalType: 'enum IPlugin.Operation', name: 'operation', type: 'uint8' },
				],
				internalType: 'struct IPlugin.TargetConfig',
				name: 'targetConfig',
				type: 'tuple',
			},
		],
		name: 'InvalidTargetConfig',
		type: 'error',
	},
	{ inputs: [{ internalType: 'uint256', name: 'proposalId', type: 'uint256' }], name: 'NonexistentProposal', type: 'error' },
	{ inputs: [{ internalType: 'uint256', name: 'proposalId', type: 'uint256' }], name: 'ProposalAdvanceForbidden', type: 'error' },
	{ inputs: [{ internalType: 'uint256', name: 'proposalId', type: 'uint256' }], name: 'ProposalAlreadyExists', type: 'error' },
	{
		inputs: [
			{ internalType: 'uint256', name: 'proposalId', type: 'uint256' },
			{ internalType: 'uint16', name: 'stageId', type: 'uint16' },
		],
		name: 'ProposalCanNotBeCancelled',
		type: 'error',
	},
	{
		inputs: [
			{ internalType: 'uint256', name: 'proposalId', type: 'uint256' },
			{ internalType: 'uint16', name: 'stageId', type: 'uint16' },
		],
		name: 'ProposalCanNotBeEdited',
		type: 'error',
	},
	{ inputs: [{ internalType: 'uint256', name: 'proposalId', type: 'uint256' }], name: 'ProposalExecutionForbidden', type: 'error' },
	{ inputs: [], name: 'StageCountZero', type: 'error' },
	{ inputs: [], name: 'StageDurationsInvalid', type: 'error' },
	{
		inputs: [
			{ internalType: 'uint64', name: 'currentStageId', type: 'uint64' },
			{ internalType: 'uint64', name: 'reportedStageId', type: 'uint64' },
		],
		name: 'StageIdInvalid',
		type: 'error',
	},
	{ inputs: [], name: 'StageThresholdsInvalid', type: 'error' },
	{ inputs: [{ internalType: 'uint64', name: '', type: 'uint64' }], name: 'StartDateInvalid', type: 'error' },
	{ inputs: [], name: 'Uint16MaxSizeExceeded', type: 'error' },
	{
		inputs: [
			{ internalType: 'uint256', name: 'proposalId', type: 'uint256' },
			{ internalType: 'uint8', name: 'currentState', type: 'uint8' },
			{ internalType: 'bytes32', name: 'allowedStates', type: 'bytes32' },
		],
		name: 'UnexpectedProposalState',
		type: 'error',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: false, internalType: 'address', name: 'previousAdmin', type: 'address' },
			{ indexed: false, internalType: 'address', name: 'newAdmin', type: 'address' },
		],
		name: 'AdminChanged',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [{ indexed: true, internalType: 'address', name: 'beacon', type: 'address' }],
		name: 'BeaconUpgraded',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [{ indexed: false, internalType: 'uint8', name: 'version', type: 'uint8' }],
		name: 'Initialized',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [{ indexed: false, internalType: 'bytes', name: 'metadata', type: 'bytes' }],
		name: 'MetadataSet',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: 'uint256', name: 'proposalId', type: 'uint256' },
			{ indexed: true, internalType: 'uint16', name: 'stageId', type: 'uint16' },
			{ indexed: true, internalType: 'address', name: 'sender', type: 'address' },
		],
		name: 'ProposalAdvanced',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: 'uint256', name: 'proposalId', type: 'uint256' },
			{ indexed: true, internalType: 'uint16', name: 'stageId', type: 'uint16' },
			{ indexed: true, internalType: 'address', name: 'sender', type: 'address' },
		],
		name: 'ProposalCanceled',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: 'uint256', name: 'proposalId', type: 'uint256' },
			{ indexed: true, internalType: 'address', name: 'creator', type: 'address' },
			{ indexed: false, internalType: 'uint64', name: 'startDate', type: 'uint64' },
			{ indexed: false, internalType: 'uint64', name: 'endDate', type: 'uint64' },
			{ indexed: false, internalType: 'bytes', name: 'metadata', type: 'bytes' },
			{
				components: [
					{ internalType: 'address', name: 'to', type: 'address' },
					{ internalType: 'uint256', name: 'value', type: 'uint256' },
					{ internalType: 'bytes', name: 'data', type: 'bytes' },
				],
				indexed: false,
				internalType: 'struct Action[]',
				name: 'actions',
				type: 'tuple[]',
			},
			{ indexed: false, internalType: 'uint256', name: 'allowFailureMap', type: 'uint256' },
		],
		name: 'ProposalCreated',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: 'uint256', name: 'proposalId', type: 'uint256' },
			{ indexed: true, internalType: 'uint16', name: 'stageId', type: 'uint16' },
			{ indexed: true, internalType: 'address', name: 'sender', type: 'address' },
			{ indexed: false, internalType: 'bytes', name: 'metadata', type: 'bytes' },
			{
				components: [
					{ internalType: 'address', name: 'to', type: 'address' },
					{ internalType: 'uint256', name: 'value', type: 'uint256' },
					{ internalType: 'bytes', name: 'data', type: 'bytes' },
				],
				indexed: false,
				internalType: 'struct Action[]',
				name: 'actions',
				type: 'tuple[]',
			},
		],
		name: 'ProposalEdited',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [{ indexed: true, internalType: 'uint256', name: 'proposalId', type: 'uint256' }],
		name: 'ProposalExecuted',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: 'uint256', name: 'proposalId', type: 'uint256' },
			{ indexed: true, internalType: 'uint16', name: 'stageId', type: 'uint16' },
			{ indexed: true, internalType: 'address', name: 'body', type: 'address' },
		],
		name: 'ProposalResultReported',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{
				components: [
					{
						components: [
							{ internalType: 'address', name: 'addr', type: 'address' },
							{ internalType: 'bool', name: 'isManual', type: 'bool' },
							{ internalType: 'bool', name: 'tryAdvance', type: 'bool' },
							{ internalType: 'enum StagedProposalProcessor.ResultType', name: 'resultType', type: 'uint8' },
						],
						internalType: 'struct StagedProposalProcessor.Body[]',
						name: 'bodies',
						type: 'tuple[]',
					},
					{ internalType: 'uint64', name: 'maxAdvance', type: 'uint64' },
					{ internalType: 'uint64', name: 'minAdvance', type: 'uint64' },
					{ internalType: 'uint64', name: 'voteDuration', type: 'uint64' },
					{ internalType: 'uint16', name: 'approvalThreshold', type: 'uint16' },
					{ internalType: 'uint16', name: 'vetoThreshold', type: 'uint16' },
					{ internalType: 'bool', name: 'cancelable', type: 'bool' },
					{ internalType: 'bool', name: 'editable', type: 'bool' },
				],
				indexed: false,
				internalType: 'struct StagedProposalProcessor.Stage[]',
				name: 'stages',
				type: 'tuple[]',
			},
		],
		name: 'StagesUpdated',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: 'uint256', name: 'proposalId', type: 'uint256' },
			{ indexed: true, internalType: 'uint16', name: 'stageId', type: 'uint16' },
			{ indexed: true, internalType: 'address', name: 'body', type: 'address' },
			{ indexed: false, internalType: 'uint256', name: 'bodyProposalId', type: 'uint256' },
		],
		name: 'SubProposalCreated',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: 'uint256', name: 'proposalId', type: 'uint256' },
			{ indexed: true, internalType: 'uint16', name: 'stageId', type: 'uint16' },
			{ indexed: true, internalType: 'address', name: 'body', type: 'address' },
			{ indexed: false, internalType: 'bytes', name: 'reason', type: 'bytes' },
		],
		name: 'SubProposalNotCreated',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{
				components: [
					{ internalType: 'address', name: 'target', type: 'address' },
					{ internalType: 'enum IPlugin.Operation', name: 'operation', type: 'uint8' },
				],
				indexed: false,
				internalType: 'struct IPlugin.TargetConfig',
				name: 'newTargetConfig',
				type: 'tuple',
			},
		],
		name: 'TargetSet',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [{ indexed: true, internalType: 'address', name: 'forwarder', type: 'address' }],
		name: 'TrustedForwarderUpdated',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [{ indexed: true, internalType: 'address', name: 'implementation', type: 'address' }],
		name: 'Upgraded',
		type: 'event',
	},
	{
		inputs: [],
		name: 'SET_METADATA_PERMISSION_ID',
		outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'SET_TARGET_CONFIG_PERMISSION_ID',
		outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'UPGRADE_PLUGIN_PERMISSION_ID',
		outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'uint256', name: '_proposalId', type: 'uint256' }],
		name: 'advanceProposal',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'uint256', name: '_proposalId', type: 'uint256' }],
		name: 'canExecute',
		outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'uint256', name: '_proposalId', type: 'uint256' }],
		name: 'canProposalAdvance',
		outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'uint256', name: '_proposalId', type: 'uint256' }],
		name: 'cancel',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'bytes', name: '_metadata', type: 'bytes' },
			{
				components: [
					{ internalType: 'address', name: 'to', type: 'address' },
					{ internalType: 'uint256', name: 'value', type: 'uint256' },
					{ internalType: 'bytes', name: 'data', type: 'bytes' },
				],
				internalType: 'struct Action[]',
				name: '_actions',
				type: 'tuple[]',
			},
			{ internalType: 'uint128', name: '_allowFailureMap', type: 'uint128' },
			{ internalType: 'uint64', name: '_startDate', type: 'uint64' },
			{ internalType: 'bytes[][]', name: '_proposalParams', type: 'bytes[][]' },
		],
		name: 'createProposal',
		outputs: [{ internalType: 'uint256', name: 'proposalId', type: 'uint256' }],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'bytes', name: '_metadata', type: 'bytes' },
			{
				components: [
					{ internalType: 'address', name: 'to', type: 'address' },
					{ internalType: 'uint256', name: 'value', type: 'uint256' },
					{ internalType: 'bytes', name: 'data', type: 'bytes' },
				],
				internalType: 'struct Action[]',
				name: '_actions',
				type: 'tuple[]',
			},
			{ internalType: 'uint64', name: '_startDate', type: 'uint64' },
			{ internalType: 'uint64', name: '', type: 'uint64' },
			{ internalType: 'bytes', name: '_data', type: 'bytes' },
		],
		name: 'createProposal',
		outputs: [{ internalType: 'uint256', name: 'proposalId', type: 'uint256' }],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [],
		name: 'customProposalParamsABI',
		outputs: [{ internalType: 'string', name: '', type: 'string' }],
		stateMutability: 'pure',
		type: 'function',
	},
	{
		inputs: [],
		name: 'dao',
		outputs: [{ internalType: 'contract IDAO', name: '', type: 'address' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'uint256', name: '_proposalId', type: 'uint256' },
			{ internalType: 'bytes', name: '_metadata', type: 'bytes' },
			{
				components: [
					{ internalType: 'address', name: 'to', type: 'address' },
					{ internalType: 'uint256', name: 'value', type: 'uint256' },
					{ internalType: 'bytes', name: 'data', type: 'bytes' },
				],
				internalType: 'struct Action[]',
				name: '_actions',
				type: 'tuple[]',
			},
		],
		name: 'edit',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'uint256', name: '_proposalId', type: 'uint256' }],
		name: 'execute',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'uint256', name: '_proposalId', type: 'uint256' },
			{ internalType: 'uint16', name: '_stageId', type: 'uint16' },
			{ internalType: 'address', name: '_body', type: 'address' },
		],
		name: 'getBodyProposalId',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'uint256', name: '_proposalId', type: 'uint256' },
			{ internalType: 'uint16', name: '_stageId', type: 'uint16' },
			{ internalType: 'address', name: '_body', type: 'address' },
		],
		name: 'getBodyResult',
		outputs: [{ internalType: 'enum StagedProposalProcessor.ResultType', name: '', type: 'uint8' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'uint256', name: '_proposalId', type: 'uint256' },
			{ internalType: 'uint16', name: '_stageId', type: 'uint16' },
			{ internalType: 'uint256', name: '_index', type: 'uint256' },
		],
		name: 'getCreateProposalParams',
		outputs: [{ internalType: 'bytes', name: '', type: 'bytes' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'getCurrentConfigIndex',
		outputs: [{ internalType: 'uint16', name: '', type: 'uint16' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'getCurrentTargetConfig',
		outputs: [
			{
				components: [
					{ internalType: 'address', name: 'target', type: 'address' },
					{ internalType: 'enum IPlugin.Operation', name: 'operation', type: 'uint8' },
				],
				internalType: 'struct IPlugin.TargetConfig',
				name: '',
				type: 'tuple',
			},
		],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'getMetadata',
		outputs: [{ internalType: 'bytes', name: '', type: 'bytes' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'uint256', name: '_proposalId', type: 'uint256' }],
		name: 'getProposal',
		outputs: [
			{
				components: [
					{ internalType: 'uint128', name: 'allowFailureMap', type: 'uint128' },
					{ internalType: 'uint64', name: 'lastStageTransition', type: 'uint64' },
					{ internalType: 'uint16', name: 'currentStage', type: 'uint16' },
					{ internalType: 'uint16', name: 'stageConfigIndex', type: 'uint16' },
					{ internalType: 'bool', name: 'executed', type: 'bool' },
					{ internalType: 'bool', name: 'canceled', type: 'bool' },
					{ internalType: 'address', name: 'creator', type: 'address' },
					{
						components: [
							{ internalType: 'address', name: 'to', type: 'address' },
							{ internalType: 'uint256', name: 'value', type: 'uint256' },
							{ internalType: 'bytes', name: 'data', type: 'bytes' },
						],
						internalType: 'struct Action[]',
						name: 'actions',
						type: 'tuple[]',
					},
					{
						components: [
							{ internalType: 'address', name: 'target', type: 'address' },
							{ internalType: 'enum IPlugin.Operation', name: 'operation', type: 'uint8' },
						],
						internalType: 'struct IPlugin.TargetConfig',
						name: 'targetConfig',
						type: 'tuple',
					},
				],
				internalType: 'struct StagedProposalProcessor.Proposal',
				name: '',
				type: 'tuple',
			},
		],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'uint256', name: '_proposalId', type: 'uint256' },
			{ internalType: 'uint16', name: '_stageId', type: 'uint16' },
		],
		name: 'getProposalTally',
		outputs: [
			{ internalType: 'uint256', name: 'approvals', type: 'uint256' },
			{ internalType: 'uint256', name: 'vetoes', type: 'uint256' },
		],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'uint256', name: '_index', type: 'uint256' }],
		name: 'getStages',
		outputs: [
			{
				components: [
					{
						components: [
							{ internalType: 'address', name: 'addr', type: 'address' },
							{ internalType: 'bool', name: 'isManual', type: 'bool' },
							{ internalType: 'bool', name: 'tryAdvance', type: 'bool' },
							{ internalType: 'enum StagedProposalProcessor.ResultType', name: 'resultType', type: 'uint8' },
						],
						internalType: 'struct StagedProposalProcessor.Body[]',
						name: 'bodies',
						type: 'tuple[]',
					},
					{ internalType: 'uint64', name: 'maxAdvance', type: 'uint64' },
					{ internalType: 'uint64', name: 'minAdvance', type: 'uint64' },
					{ internalType: 'uint64', name: 'voteDuration', type: 'uint64' },
					{ internalType: 'uint16', name: 'approvalThreshold', type: 'uint16' },
					{ internalType: 'uint16', name: 'vetoThreshold', type: 'uint16' },
					{ internalType: 'bool', name: 'cancelable', type: 'bool' },
					{ internalType: 'bool', name: 'editable', type: 'bool' },
				],
				internalType: 'struct StagedProposalProcessor.Stage[]',
				name: '',
				type: 'tuple[]',
			},
		],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'getTargetConfig',
		outputs: [
			{
				components: [
					{ internalType: 'address', name: 'target', type: 'address' },
					{ internalType: 'enum IPlugin.Operation', name: 'operation', type: 'uint8' },
				],
				internalType: 'struct IPlugin.TargetConfig',
				name: '',
				type: 'tuple',
			},
		],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'getTrustedForwarder',
		outputs: [{ internalType: 'address', name: '', type: 'address' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'address', name: '_account', type: 'address' }],
		name: 'hasAdvancePermission',
		outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'address', name: '_account', type: 'address' }],
		name: 'hasExecutePermission',
		outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'uint256', name: '_proposalId', type: 'uint256' }],
		name: 'hasSucceeded',
		outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'implementation',
		outputs: [{ internalType: 'address', name: '', type: 'address' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'contract IDAO', name: '_dao', type: 'address' },
			{ internalType: 'address', name: '_trustedForwarder', type: 'address' },
			{
				components: [
					{
						components: [
							{ internalType: 'address', name: 'addr', type: 'address' },
							{ internalType: 'bool', name: 'isManual', type: 'bool' },
							{ internalType: 'bool', name: 'tryAdvance', type: 'bool' },
							{ internalType: 'enum StagedProposalProcessor.ResultType', name: 'resultType', type: 'uint8' },
						],
						internalType: 'struct StagedProposalProcessor.Body[]',
						name: 'bodies',
						type: 'tuple[]',
					},
					{ internalType: 'uint64', name: 'maxAdvance', type: 'uint64' },
					{ internalType: 'uint64', name: 'minAdvance', type: 'uint64' },
					{ internalType: 'uint64', name: 'voteDuration', type: 'uint64' },
					{ internalType: 'uint16', name: 'approvalThreshold', type: 'uint16' },
					{ internalType: 'uint16', name: 'vetoThreshold', type: 'uint16' },
					{ internalType: 'bool', name: 'cancelable', type: 'bool' },
					{ internalType: 'bool', name: 'editable', type: 'bool' },
				],
				internalType: 'struct StagedProposalProcessor.Stage[]',
				name: '_stages',
				type: 'tuple[]',
			},
			{ internalType: 'bytes', name: '_pluginMetadata', type: 'bytes' },
			{
				components: [
					{ internalType: 'address', name: 'target', type: 'address' },
					{ internalType: 'enum IPlugin.Operation', name: 'operation', type: 'uint8' },
				],
				internalType: 'struct IPlugin.TargetConfig',
				name: '_targetConfig',
				type: 'tuple',
			},
		],
		name: 'initialize',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'address', name: '_forwarder', type: 'address' }],
		name: 'isTrustedForwarder',
		outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'pluginType',
		outputs: [{ internalType: 'enum IPlugin.PluginType', name: '', type: 'uint8' }],
		stateMutability: 'pure',
		type: 'function',
	},
	{
		inputs: [],
		name: 'proposalCount',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'protocolVersion',
		outputs: [{ internalType: 'uint8[3]', name: '', type: 'uint8[3]' }],
		stateMutability: 'pure',
		type: 'function',
	},
	{
		inputs: [],
		name: 'proxiableUUID',
		outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'uint256', name: '_proposalId', type: 'uint256' },
			{ internalType: 'uint16', name: '_stageId', type: 'uint16' },
			{ internalType: 'enum StagedProposalProcessor.ResultType', name: '_resultType', type: 'uint8' },
			{ internalType: 'bool', name: '_tryAdvance', type: 'bool' },
		],
		name: 'reportProposalResult',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'bytes', name: '_metadata', type: 'bytes' }],
		name: 'setMetadata',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{
				components: [
					{ internalType: 'address', name: 'target', type: 'address' },
					{ internalType: 'enum IPlugin.Operation', name: 'operation', type: 'uint8' },
				],
				internalType: 'struct IPlugin.TargetConfig',
				name: '_targetConfig',
				type: 'tuple',
			},
		],
		name: 'setTargetConfig',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'address', name: '_forwarder', type: 'address' }],
		name: 'setTrustedForwarder',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'uint256', name: '_proposalId', type: 'uint256' }],
		name: 'state',
		outputs: [{ internalType: 'enum StagedProposalProcessor.ProposalState', name: '', type: 'uint8' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'bytes4', name: '_interfaceId', type: 'bytes4' }],
		name: 'supportsInterface',
		outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{
				components: [
					{
						components: [
							{ internalType: 'address', name: 'addr', type: 'address' },
							{ internalType: 'bool', name: 'isManual', type: 'bool' },
							{ internalType: 'bool', name: 'tryAdvance', type: 'bool' },
							{ internalType: 'enum StagedProposalProcessor.ResultType', name: 'resultType', type: 'uint8' },
						],
						internalType: 'struct StagedProposalProcessor.Body[]',
						name: 'bodies',
						type: 'tuple[]',
					},
					{ internalType: 'uint64', name: 'maxAdvance', type: 'uint64' },
					{ internalType: 'uint64', name: 'minAdvance', type: 'uint64' },
					{ internalType: 'uint64', name: 'voteDuration', type: 'uint64' },
					{ internalType: 'uint16', name: 'approvalThreshold', type: 'uint16' },
					{ internalType: 'uint16', name: 'vetoThreshold', type: 'uint16' },
					{ internalType: 'bool', name: 'cancelable', type: 'bool' },
					{ internalType: 'bool', name: 'editable', type: 'bool' },
				],
				internalType: 'struct StagedProposalProcessor.Stage[]',
				name: '_stages',
				type: 'tuple[]',
			},
		],
		name: 'updateStages',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'address', name: 'newImplementation', type: 'address' }],
		name: 'upgradeTo',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'address', name: 'newImplementation', type: 'address' },
			{ internalType: 'bytes', name: 'data', type: 'bytes' },
		],
		name: 'upgradeToAndCall',
		outputs: [],
		stateMutability: 'payable',
		type: 'function',
	},
] as const;
