export const SwapBridgeMorphoV1_ABI = [
	{
		inputs: [
			{ internalType: 'contract Stablecoin', name: '_stable', type: 'address' },
			{ internalType: 'contract IERC4626', name: '_vault', type: 'address' },
			{ internalType: 'uint256', name: '_mintCap', type: 'uint256' },
			{ internalType: 'uint24', name: '_swapInFeePPM', type: 'uint24' },
			{ internalType: 'uint24', name: '_swapOutFeePPM', type: 'uint24' },
		],
		stateMutability: 'nonpayable',
		type: 'constructor',
	},
	{ inputs: [{ internalType: 'uint24', name: 'feePPM', type: 'uint24' }], name: 'InvalidFee', type: 'error' },
	{
		inputs: [
			{ internalType: 'uint256', name: 'requested', type: 'uint256' },
			{ internalType: 'uint256', name: 'cap', type: 'uint256' },
		],
		name: 'MintCapExceeded',
		type: 'error',
	},
	{ inputs: [{ internalType: 'uint256', name: 'validAt', type: 'uint256' }], name: 'ReconcileTooSoon', type: 'error' },
	{ inputs: [], name: 'ReentrancyGuardReentrantCall', type: 'error' },
	{ inputs: [{ internalType: 'address', name: 'token', type: 'address' }], name: 'SafeERC20FailedOperation', type: 'error' },
	{
		anonymous: false,
		inputs: [
			{ indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256' },
			{ indexed: false, internalType: 'uint256', name: 'totalRevenue', type: 'uint256' },
			{ indexed: false, internalType: 'uint256', name: 'totalMinted', type: 'uint256' },
		],
		name: 'Revenue',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: 'address', name: 'target', type: 'address' },
			{ indexed: false, internalType: 'uint256', name: 'amountCoin', type: 'uint256' },
			{ indexed: false, internalType: 'uint256', name: 'amountStable', type: 'uint256' },
			{ indexed: false, internalType: 'uint256', name: 'fee', type: 'uint256' },
		],
		name: 'SwapIn',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: 'address', name: 'target', type: 'address' },
			{ indexed: false, internalType: 'uint256', name: 'amountStable', type: 'uint256' },
			{ indexed: false, internalType: 'uint256', name: 'amountCoin', type: 'uint256' },
			{ indexed: false, internalType: 'uint256', name: 'fee', type: 'uint256' },
		],
		name: 'SwapOut',
		type: 'event',
	},
	{
		inputs: [],
		name: 'coin',
		outputs: [{ internalType: 'contract IERC20Metadata', name: '', type: 'address' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'lastReconciledAt',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'mintCap',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{ inputs: [], name: 'reconcile', outputs: [], stateMutability: 'nonpayable', type: 'function' },
	{
		inputs: [{ internalType: 'bool', name: 'allowMinting', type: 'bool' }],
		name: 'reconcile',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [],
		name: 'stable',
		outputs: [{ internalType: 'contract Stablecoin', name: '', type: 'address' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'uint256', name: 'amount', type: 'uint256' }],
		name: 'swapIn',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [],
		name: 'swapInFeePPM',
		outputs: [{ internalType: 'uint24', name: '', type: 'uint24' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'address', name: 'target', type: 'address' },
			{ internalType: 'uint256', name: 'amount', type: 'uint256' },
		],
		name: 'swapInTo',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'uint256', name: 'amount', type: 'uint256' }],
		name: 'swapOut',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [],
		name: 'swapOutFeePPM',
		outputs: [{ internalType: 'uint24', name: '', type: 'uint24' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'address', name: 'target', type: 'address' },
			{ internalType: 'uint256', name: 'amount', type: 'uint256' },
		],
		name: 'swapOutTo',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [],
		name: 'totalAssets',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'totalMinted',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'totalRevenue',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'vault',
		outputs: [{ internalType: 'contract IERC4626', name: '', type: 'address' }],
		stateMutability: 'view',
		type: 'function',
	},
] as const;
